python3 ./bots/1NC/massdm/bot1.py ./bots/1NC/massdm/config/bot_config_1.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_2.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_3.json 20 & 
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_4.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_5.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_6.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_7.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_8.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_9.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_10.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_11.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_12.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_13.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_14.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_15.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_16.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_17.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_18.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_19.json 20 &
python3 ./bots/1NC/massdm/bot2.py ./bots/1NC/massdm/config/bot_config_20.json 20 &