CREATE TABLE IF NOT EXISTS giveaway (
	CHANNEL integer NOT NULL DEFAULT 0,
	ID integer NOT NULL DEFAULT 0,
	ENDING text NOT NULL,
	ITEM text NOT NULL,
	AUTHOR integer NOT NULL DEFAULT 0,
	PARTICIPANTS text,
	PRIMARY KEY(ID, PARTICIPANTS)
);
