CREATE TABLE IF NOT EXISTS guilds (
	GUILD_ID integer PRIMARY KEY,
	PREFIX text DEFAULT "+"
);

CREATE TABLE IF NOT EXISTS exp (
	USER_IDS integer PRIMARY KEY,
	XP integer DEFAULT 0,
	LEVELS integer DEFAULT 0,
	XP_BLOCK text DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mutes (
	USER_IDS integer PRIMARY KEY,
	ROLE_IDS text,
	END_TIME text
);

CREATE TABLE IF NOT EXISTS starboard (
	ROOT_MESSAGE_ID integer PRIMARY KEY,
	STAR_MESSAGE_ID integer,
	STARS integer DEFAULT 1
);